server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
  error:
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부
    whitelabel:
      enabled: false

spring:
  devtools:
    restart:
      enabled: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  


      
   
 
      
